### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by killmenot** [robtweed/qewd#10]
Hey @robtweed 

Could you please explain me the logic of the following lines?
https://github.com/robtweed/qewd/blob/71a04572c8dbd752bca0ef640fefa91f7752ddcd/lib/appHandler.js#L303-L305

is it correct to pass `application` to `loadModule`? I have a feeling that `messageObj.service` should be passed there

**Comment by robtweed** [comment]
OK - this is the correct logic - it's all a bit complex at this point, but what's happening here is that you're normally not allowed to load fragments from other applications.  Whether or not you're allowed to use another application as a service is defined in the application's module.  

So what this is doing is - if a request has come in for a fragment from another service, and we don't know what services are allowed for that application, it means we haven't yet loaded the application module, so load it now.  When getFragment is called, it will then have the information to know whether or not the fragment is allowed to be fetched

Hopefully that makes sense.  Anyway the bottom line is that the code is correct
