### ISSUE TITLE
frag path

### ISSUE THREAD

**Issue by killmenot** [robtweed/qewd#13]
https://github.com/robtweed/qewd/blob/71a04572c8dbd752bca0ef640fefa91f7752ddcd/lib/getFragment.js#L42

can be refactored to `path.join(wsRootPath, application, fragmentName)`

**Comment by killmenot** [comment]
Same for
```js
fragPath = servicePaths[service] + path.sep + 'fragments' + path.sep + fragmentName;
```
can be rewritten to
```js
fragPath = path.join(servicePaths[service], 'fragments', fragmentName);
```

**Comment by robtweed** [comment]
I suppose that's worth doing, yes.  Not much in it really IMO
