### ISSUE TITLE
fs.exists is deprecated

### ISSUE THREAD

**Issue by killmenot** [robtweed/qewd#15]
https://github.com/robtweed/qewd/blob/71a04572c8dbd752bca0ef640fefa91f7752ddcd/lib/getFragment.js#L63-L66

https://nodejs.org/api/fs.html#fs_fs_exists_path_callback

**Comment by robtweed** [comment]
Indeed - might be worth replacing with the synchronous version (fs.existsSync) which hasn't been deprecated
