### ISSUE TITLE
Handle boolean property correctly

### ISSUE THREAD

**Issue by killmenot** [robtweed/qewd#16]
Hey @robtweed 
https://github.com/robtweed/qewd/blob/71a04572c8dbd752bca0ef640fefa91f7752ddcd/lib/jwtHandler.js#L330-L340

What if payload contains `false`, `''` or `null`? In this case false be returned by `getProperty`. Maybe it's better to have here `if (typeof payload[propertyName] === 'undefined'`? Ofc if it makes sense here

**Comment by robtweed** [comment]
yes - typeof payload[propertyName] === 'undefined' would be better in this situation
