### ISSUE TITLE
master-koa vs. master-express

### ISSUE THREAD

**Issue by killmenot** [robtweed/qewd#21]
koa has 2 routes for ajax (GET and POST)
https://github.com/robtweed/qewd/blob/master/lib/master-koa.js#L94-L101

express has only 2 route for POST
https://github.com/robtweed/qewd/blob/master/lib/master-express.js#L60-L64

@robtweed is it correct?

**Comment by robtweed** [comment]
Yes that's actually fine - strictly speaking only POST is used by ewd-client, so the GET in the koa.js logic is somewhat redundant
