### ISSUE TITLE
Question about DELETE route for master-koa

### ISSUE THREAD

**Issue by killmenot** [robtweed/qewd#22]
Hi @robtweed 

Please take a look:
https://github.com/robtweed/qewd/blob/b74a7c5f796cfebaa26081c2818164bd10bd4c1c/lib/master-koa.js#L151-L164

All verbs are used two times for `'/:type` and `'/:type/*'` but DELETE is used only once (for `'/:type/*'`). Is it correct?

**Comment by killmenot** [comment]
The second question related to this snippet of the code is:
all routes runs in order:
1 - 'VERB ' + path + '/:type'
2 - 'VERB ' + path + '/:type/*'

but POST in 
1 - 'VERB ' + path + '/:type/*'
2 - 'VERB ' + path + '/:type'

Is it correct?

**Comment by robtweed** [comment]
You're right - the DELETE should appear twice like the others

**Comment by robtweed** [comment]
Regarding your second question, the order shouldn't matter, but align them if you wish
