### ISSUE TITLE
Question about config/params

### ISSUE THREAD

**Issue by killmenot** [robtweed/qewd#23]
HI @robtweed https://github.com/robtweed/qewd/blob/b74a7c5f796cfebaa26081c2818164bd10bd4c1c/lib/master.js#L119-L124

Should it be `if (params.resilientMode) {` or `if (config.resilientMode) {`?

**Comment by killmenot** [comment]
Another such snippet
https://github.com/robtweed/qewd/blob/master/lib/master.js#L150

**Comment by robtweed** [comment]
The code is correct as it is.  params.resilientMode is the incoming user setting.  config.resilientMode is what is passed to the worker processes
