### ISSUE TITLE
Question about using resilientMode.documentName in resilientMode.js

### ISSUE THREAD

**Issue by killmenot** [robtweed/qewd#25]
Hi @robtweed 

Sometimes in resilientMode.js I see different usage of `resilientMode.documentName`

First way:
https://github.com/robtweed/qewd/blob/master/lib/resilientMode.js#L37

Second way:
https://github.com/robtweed/qewd/blob/master/lib/resilientMode.js#L157

But it looks like they point to the same
https://github.com/robtweed/qewd/blob/master/lib/master.js#L155

I think it can be unified.

**Comment by robtweed** [comment]
No they can't be unified - this.resilientMode.documentName is used by the master process.  The longer reference is used by worker processes.  Please leave as is

**Comment by killmenot** [comment]
OK
