### ISSUE TITLE
Question about socketClient logic

### ISSUE THREAD

**Issue by killmenot** [robtweed/qewd#28]
Hi @robtweed 

Please take a look at `message` obj format when socket client `connected` event is emitted -> https://github.com/robtweed/qewd/blob/master/lib/socketClient.js#L108. `connected` event emitted `ewdjs` in the end

However, when `ewdjs` is emitted, we check message type and then get token by taken `messageObj.message.token` -> https://github.com/robtweed/qewd/blob/master/lib/socketClient.js#L68

Is it correct?

**Comment by robtweed** [comment]
These are 2 different messages for 2 different scenarios.  What it's doing is correct
