### ISSUE TITLE
Docker Hub name is wrong in README?

### ISSUE THREAD

**Issue by geoidesic** [robtweed/qewd#42]
Hi Rob,

I'm trying to have a go with QEWD-UP. The read me shows as attached:
<img width="951" alt="Screenshot 2021-04-02 at 14 45 01" src="https://user-images.githubusercontent.com/4637995/113420942-1dede300-93c2-11eb-8796-90211779f263.png">

1. I searched docker hub but couldn't find anything with that name? 
2. Also you have a double parenthesis in that bit of README that could probably use a tidy-up :)

**Comment by robtweed** [comment]
Yep - sorry, should be rtweed/qewd-server and rtweed/qewd-server-rpi 

README will be changed very soon to fix
